name: release

on:
  release:
    types: [published]

jobs:
  test_release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
    - uses: cycodelabs/cimon-action@v0
      with:
        prevent: true
        fail-on-error: true
        allowed-ips: >
          3.216.34.172
          3.228.146.75
          18.206.20.10
          18.210.197.188
          18.215.138.58
          34.194.164.123
          34.205.13.154
          44.196.175.70
          44.205.64.79
          52.1.184.176
          52.3.144.121
          54.165.156.197
          104.16.100.207
          104.16.101.207
          104.16.102.207
          104.16.103.207
          104.16.104.207
        allowed-hosts: >
          files.pythonhosted.org
          pypi.org
          raw.githubusercontent.com

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Download Latest Release
      run: |
        curl -s https://raw.githubusercontent.com/CycodeLabs/raven/f020094d175ab5cd0eb10442c6f7728485cc6903/install.sh | bash

    - name: Setup environment
      working-directory: raven
      run: make setup

    - name: Download Organization
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        raven download org --token $GITHUB_TOKEN --org-name RavenIntegrationTests
        raven index
        raven report --format json | jq > /dev/null

  publish:
    name: Release to PyPI
    runs-on: ubuntu-latest
    needs: test_release
    permissions:
      id-token: write
    if: ${{ startsWith(github.ref_name, 'v') }}
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          fail-on-error: true
          allowed-ips: >
            3.216.34.172
            3.228.146.75
            18.206.20.10
            18.210.197.188
            18.215.138.58
            34.194.164.123
            34.205.13.154
            44.196.175.70
            44.205.64.79
            52.1.184.176
            52.3.144.121
            54.165.156.197
            104.16.100.207
            104.16.101.207
            104.16.102.207
            104.16.103.207
            104.16.104.207
          allowed-hosts: >
            files.pythonhosted.org
            pypi.org
            raw.githubusercontent.com

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        env:
          RAVEN_VERSION: ${{ github.ref_name }}
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@sha256:b7f401de30cb6434a1e19f805ff006643653240e # v1.8.10